// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObjects.Models;

public partial class AccountMember
{
    public string MemberId { get; set; }

    public string MemberPassword { get; set; }

    public string FullName { get; set; }

    public string EmailAddress { get; set; }

    public int MemberRole { get; set; }
}